version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # change this to a strong password
      MYSQL_DATABASE: todolist
      MYSQL_USER: user                   # optional, can use root only
      MYSQL_PASSWORD: userpassword       # optional
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./todos.sql:/docker-entrypoint-initdb.d/todos.sql:ro

volumes:
  db_data:
